.github/workflows/build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -4,36 +4,52 @@ on:
   workflow_dispatch:
 
 jobs:
-  build-all:
+  build:
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        board: [aaw2b]
 
     steps:
-    - name: Checkout
-      uses: actions/checkout@v4
-      with:
-        submodules: recursive
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          submodules: recursive
 
-    - name: Build Docker image
-      run: ./docker-dev.sh build
+      - name: Build Docker image
+        run: CONTAINER_ENGINE=docker ./docker-dev.sh build
 
-    - name: Build all boards sequentially
-      run: |
-        set -e
-        mkdir images
-        for board in aaw2b rpi02w rpi0w rpi3a rpi4 rpi5; do
-          echo "Building board: $board"
-          ./docker-dev.sh "$board"
-          IMG=buildroot/output/"$board"/images/sdcard.img
-          if [[ -f "$IMG" ]]; then
-            xz -c "$IMG" > images/"$board"-sdcard.img.xz
+      - name: Build image for ${{ matrix.board }}
+        run: |
+          set -e
+          mkdir images
+          echo "Building board: ${{ matrix.board }}"
+          CONTAINER_ENGINE=docker ./docker-dev.sh "${{ matrix.board }}"
+          IMAGE_DIR=buildroot/output/${{ matrix.board }}/images
+          if [[ "${{ matrix.board }}" == "aaw2b" ]]; then
+            TAR_NAME=images/${{ matrix.board }}-images.tar.xz
+            echo "Compressing entire images directory for aaw2b..."
+            tar -cJf "$TAR_NAME" -C "$IMAGE_DIR" .
           else
-            echo "WARNING: Image $IMG not found!"
-            exit 1
+            IMG="$IMAGE_DIR/sdcard.img"
+            if [[ -f "$IMG" ]]; then
+              xz -c "$IMG" > images/${{ matrix.board }}-sdcard.img.xz
+            else
+              echo "WARNING: Image $IMG not found!"
+              #exit 1
+            fi
           fi
-        done
 
-    - name: Upload a Build Artifact
-      uses: actions/upload-artifact@v4
-      with:
-        name: aa-proxy-rs
-        path: ./images
+      - name: Upload Artifact for ${{ matrix.board }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ matrix.board }}-sdcard
+          path: ${{ matrix.board == 'aaw2b' && format('images/{0}-images.tar.xz', matrix.board) || format('images/{0}-sdcard.img.xz', matrix.board) }}
+
+  merge:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - uses: actions/upload-artifact/merge@v4
+        with:
+          name: aa-proxy-rs-merged
